app_name: "Paleo Merge"
bundle_id: "com.company.paleomerge"
icon_path: "Icon.png"
team_id: ""
app_version: "1.0.0"
build_number: "1"
podfile_path: "scripts/Podfile"
nse_swift_path: "scripts/NotificationService.swift"
nse_plist_path: ""
